### ISSUE TITLE
请问能在iOS11 上工作么?

### ISSUE THREAD

**Issue by pengbins** [JustinYangJing/AirPlayTest#1]

**Comment by pengbins** [comment]
我这边测试发现用MPAVRoutingViewController 的 pickRoute 只能选中音频输出设备, 屏幕镜像无法选中, 请问, 有啥办法找到选中屏幕镜像的方法么?

**Comment by JustinYangJing** [comment]
可以，https://github.com/pamepros/AirplaySelector

**Comment by duanhai** [comment]
@JustinYangJing 你给的那个连接我拖入对应的头文件,在iOS11上还是无法编译通过呢.

**Comment by pengbins** [comment]
我这边也没编译过, 里面用到的一个类被移除了
